/* eslint-disable prettier/prettier */
export const REDIS_SUBSCRIBER_CLIENT = 'REDIS_SUBSCRIBER_CLIENT';
export const REDIS_PUBLISHER_CLIENT = 'REDIS_PUBLISHER_CLIENT';
export const REDIS_CHAT_SUSCRIBER_CLIENT = Symbol('CHATS_SUSCRIBER')